### ISSUE TITLE
sktp-2plus.words is required for building but missing from the repository

### ISSUE THREAD

**Issue by Traubert** [koskenni/ofitwol#2]
Under `ofitwol/`, the `Makefile` says:

`WORDS=~/Dropbox/lang/fin/sktp-2plus.words`

This looks like a temporary local source; that file isn't included in the repository.

**Comment by koskenni** [comment]
Indeed, the file sktp-2plus.words is not in the repository because I think that I may not publish it. That word list is trimmed out of a word list computed out of a corpus which is identified by the URN  http://urn.fi/urn:nbn:fi:lb-2016050206. There is another word list of Early Modern Standard Finnish, see http://kaino.kotus.fi/sanat/taajuuslista/vns_frek.zip . I would be very happy to include such lists in the repository but I probably cannot.
